config/routes.rb
Rails.application.routes.draw do
  resources :likes
  resources :followings
  resources :users,  except: [:new]
  resource :sessions, only: [:create, :destroy]
  resources :opinions, only: [:index, :create] do
    resources :comments, only: [:create]
    resources :likes, only: [:create, :destroy]
  end

  root to: 'opinions#index'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  get '/tlogin', to: 'sessions#tnew'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  post '/create_opinion', to: 'opinions#create', as: :new_opinion
  get '/follow/:followed_id', to: 'followings#create', as: :follow
  delete '/:followed_id', to: 'followings#destroy', as: :unfollow
  get '/reply', to: 'comments#new', as: :new_reply
 end

app/models/following.rb
class Following < ApplicationRecord
  validates :follower_id, presence: true
  validates :followed_id, presence: true
  belongs_to :Follower, foreign_key: 'follower_id', class_name: 'User'
  belongs_to :Followed, foreign_key: 'followed_id', class_name: 'User'

  def self.unfollow(sender_id, receiver_id)
    Following.where(follower_id: sender_id).where(followed_id: receiver_id)[0]
  end
end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController
  def create
    Following.create(follower_id: current_user.id, followed_id: params[:followed_id])
    redirect_to user_path(params[:followed_id])
  end

  def destroy
    @followings = Following.unfollow(current_user.id, params[:followed_id])
    @followings.destroy
    redirect_to user_path(params[:followed_id])
  end
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/views/followings/_form.html.erb
<%= simple_form_for(@following) do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
    <%= f.input :follower_id %>
    <%= f.input :followed_id %>
  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/followings/edit.html.erb
<h1>Editing Following</h1>
<%= render 'form', following: @following %>
<%= link_to 'Show', @following %> |
<%= link_to 'Back', followings_path %>

app/views/followings/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Followings</h1>
<table>
  <thead>
    <tr>
      <th>Follower</th>
      <th>Followed</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @followings.each do |following| %>
      <tr>
        <td><%= following.follower_id %></td>
        <td><%= following.followed_id %></td>
        <td><%= link_to 'Show', following %></td>
        <td><%= link_to 'Edit', edit_following_path(following) %></td>
        <td><%= link_to 'Destroy', following, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Following', new_following_path %>

app/views/followings/new.html.erb
<h1>New Following</h1>
<%= render 'form', following: @following %>
<%= link_to 'Back', followings_path %>

app/views/followings/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Follower:</strong>
  <%= @following.follower_id %>
</p>
<p>
  <strong>Followed:</strong>
  <%= @following.followed_id %>
</p>
<%= link_to 'Edit', edit_following_path(@following) %> |
<%= link_to 'Back', followings_path %>