config/routes.rb
Rails.application.routes.draw do
  resources :likes
  resources :followings
  resources :users,  except: [:new]
  resource :sessions, only: [:create, :destroy]
  resources :opinions, only: [:index, :create] do
    resources :comments, only: [:create]
    resources :likes, only: [:create, :destroy]
  end

  root to: 'opinions#index'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  get '/tlogin', to: 'sessions#tnew'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  post '/create_opinion', to: 'opinions#create', as: :new_opinion
  get '/follow/:followed_id', to: 'followings#create', as: :follow
  delete '/:followed_id', to: 'followings#destroy', as: :unfollow
  get '/reply', to: 'comments#new', as: :new_reply
 end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true, length: { maximum: 50, too_long: '50 characters maximum allowed.' }
  belongs_to :commentor, foreign_key: 'commentor_id', class_name: 'User'
  belongs_to :opinion
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @opinion = Opinion.find(params[:opinion_id])
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.opinion_id = params[:opinion_id]
    @comment.commentor = current_user
    if @comment.save
      redirect_to opinions_path, notice: 'You replied to a twid'
    else
      redirect_to opinions_path, alert: @comment.errors.full_messages.join('. ').to_s
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def commentor_image(comment)
    if comment.commentor[:photo].nil?
      gravatar_for(comment.commentor, size: 56)
    else
      cl_image_tag(comment.commentor.photo.commentor_photo.url)
    end
  end
end

app/views/comments/_comment.html.erb
<% collection.each do |comment| %>
  <div class="reply-bg d-flex align-items-center my-2 ">
    <%= link_to user_path(comment.commentor), class:'img-link' do %>
      <picture class="commentor-img pr-2">
        <%= commentor_image(comment) %>
      </picture>
    <% end %>
    <div class=" comment-bg d-flex flex-column ">
      <h6 class="commentor-details mb-1"><span class="text-capitalize">reply</span> by <span class="txt-bold text-capitalize"><%= link_to "#{comment.commentor.fullname}", user_path(comment.commentor), class:'commentor-name' %></span><span>, on <%= comment.created_at.strftime("%Y/%m/%d") %></span></h6>
      <h6 class="reply-content mb-0"><%= comment.content %></h6>
    </div>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= simple_form_for(@comment, remote: true) do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
    <%= f.input :author_id %>
    <%= f.input :opinion_id %>
    <%= f.input :content %>
  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/comments/_new.html.erb
<div class="modal-header">
  <h4 class="modal-title replymodal-title" id="myModalLabel"><span class="">Respond to twid, by</span><span class="text-capitalize"> <%= @opinion.author.fullname %></span></h4>
  <button type="button" class="close" data-dismiss="modal">x</button>
</div>
<div class="modal-body">
  <%= render partial: 'shared/comment_form', locals: { comment: @opinion.comments.new, opinion: @opinion } %>
</div>
<div class="modal-footer">
  <div class="mfooter-conent d-flex align-items-center justify-content-end">
    <div class="">
      <h6 class="my-0"><span class="abbrv">Twid</span> - tell what I'm doing!</h6>
    </div>
  </div>
</div>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>
<%= render 'form', comment: @comment %>
<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Comments</h1>
<table>
  <thead>
    <tr>
      <th>commentor</th>
      <th>Opinion</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.author_id %></td>
        <td><%= comment.opinion_id %></td>
        <td><%= comment.content %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>
<%= render 'form', comment: @comment %>
<%= link_to 'Back', comments_path %>

app/views/comments/new.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'new') %>");
$("#modal-window").modal();

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>author:</strong>
  <%= @comment.author_id %>
</p>
<p>
  <strong>Opinion:</strong>
  <%= @comment.opinion_id %>
</p>
<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>
<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>