config/routes.rb
Rails.application.routes.draw do
  resources :likes
  resources :followings
  resources :users,  except: [:new]
  resource :sessions, only: [:create, :destroy]
  resources :opinions, only: [:index, :create] do
    resources :comments, only: [:create]
    resources :likes, only: [:create, :destroy]
  end

  root to: 'opinions#index'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  get '/tlogin', to: 'sessions#tnew'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  post '/create_opinion', to: 'opinions#create', as: :new_opinion
  get '/follow/:followed_id', to: 'followings#create', as: :follow
  delete '/:followed_id', to: 'followings#destroy', as: :unfollow
  get '/reply', to: 'comments#new', as: :new_reply
 end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 50 }
  validates :fullname, presence: true, length: { minimum: 3, maximum: 80 }
  has_many :opinions, foreign_key: 'author_id', class_name: 'Opinion'
  has_many :followed, foreign_key: 'follower_id', class_name: 'Following'
  has_many :followers, foreign_key: 'followed_id', class_name: 'Following'
  has_many :following, through: :followed, source: :Followed
  has_many :comments, foreign_key: 'commentor_id', class_name: 'Comment'
  has_many :likes, dependent: :destroy
  before_save { self.username = username.downcase }
  mount_uploader :photo, ImageUploader
  mount_uploader :cover_img, ImageUploader

  def self.user_followers(id, curr_user_id)
    Following.where(followed_id: id).where.not(follower_id: curr_user_id).order(created_at: :desc).limit(5)
  end

  def self.all_users(user_id)
    User.where('id != ?', user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @opinion = Opinion.new
    @opinions = @user.opinions.order('created_at DESC').includes([:author]).limit(5)
    @followers = User.user_followers(params[:id], current_user.id)
  end

  def new
    session[:user_id] = nil if logged_in?
    @user = User.new
    respond_to do |format|
      format.html
      format.js
    end
  end

  def edit; end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = 'Account was successfully created. Please Login'
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:fullname, :username, :photo, :cover_img)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def cover_image(user)
    if user[:photo].nil?
      raw('<img src="https://user-images.githubusercontent.com/12745474/112985530-d2cc9980-914f-11eb-8f02-3e9d443a06f1.png">')
    else
      cl_image_tag(user.cover_img.cover.url, class: 'cover-img')
    end
  end

  def profile_image(user)
    if user[:photo].nil?
      gravatar_for(user, size: 96)
    else
      cl_image_tag(user.photo.profile.url)
    end
  end

  def follower_photo(follower)
    if follower.Follower[:photo].nil?
      gravatar_for(follower.Follower, size: 64)
    else
      cl_image_tag(follower.Follower.photo.follow.url)
    end
  end

  def follow_toggle(follower)
    if current_user.followed.any? { |person| person.followed_id == follower.Follower.id }
      link_to(unfollow_path(follower.Follower), method: :delete) do
        raw('<i class="follow-picon feather-32 minus-circle"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-minus-circle follow-picon feather-32"><circle cx="12" cy="12" r="10"></circle><line x1="8" y1="12" x2="16" y2="12"></line></svg></i>')
      end
    else
      link_to(follow_path(follower.Follower)) do
        raw('<i class="follow-picon feather-32 plus-circle"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-plus-circle follow-picon feather-32"><circle cx="12" cy="12" r="10"></circle><line x1="12" y1="8" x2="12" y2="16"></line><line x1="8" y1="12" x2="16" y2="12"></line></svg></i>')
      end
    end
  end

  def followprofile_toggle
    if current_user.id == @user.id
      content_tag(:div, class: %w[flex-fill d-flex flex-column align-items-end justify-content-center]) do
        raw('<div class="followicon-dim follow-picon hide-item"></div>')
      end
    elsif current_user.followed.any? { |person| person.followed_id == @user.id }
      content_tag(:div, class: %w[flex-fill d-flex flex-column align-items-end justify-content-center]) do
        link_to(unfollow_path(@user), id: 'unfollow_path', method: :delete) do
          raw('<i class="follow-picon py-1 feather-32 minus-circle"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-minus-circle feather-32"><circle cx="12" cy="12" r="10"></circle><line x1="8" y1="12" x2="16" y2="12"></line></svg></i>')
        end
      end
    else
      content_tag(:div, class: %w[flex-fill d-flex flex-column align-items-end justify-content-center]) do
        link_to(follow_path(@user), id: 'follow_path') do
          raw('<i class="follow-picon  feather-32 plus-circle py-1"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-plus-circle follow-picon feather-32"><circle cx="12" cy="12" r="10"></circle><line x1="12" y1="8" x2="12" y2="16"></line><line x1="8" y1="12" x2="16" y2="12"></line></svg></i>')
        end
      end
    end
  end

  def userlisticon_toggle
    if current_user.id == @user.id
      content_tag(:div, class: %w[flex-fill d-flex flex-column align-items-end justify-content-center]) do
        raw('<div class="followicon-dim follow-picon hide-item"></div>')
      end
    else
      raw('<i class="follow-licon feather-32 list"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-list follow-licon feather-32"><line x1="8" y1="6" x2="21" y2="6"></line><line x1="8" y1="12" x2="21" y2="12"></line><line x1="8" y1="18" x2="21" y2="18"></line><line x1="3" y1="6" x2="3.01" y2="6"></line><line x1="3" y1="12" x2="3.01" y2="12"></line><line x1="3" y1="18" x2="3.01" y2="18"></line></svg></i>')
    end
  end
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <%= error_msg(user) %>
  <div class="field">
    <%= form.label :fullname %>
    <%= form.text_area :fullname %>
  </div>
  <div class="field">
    <%= form.label :username %>
    <%= form.text_area :username %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_new.html.erb
<div class="modal-header">
  <h4 class="modal-title text-capitalize" id="myModalLabel">signup to twidder</h4>
  <button type="button" class="close" data-dismiss="modal">x</button>
</div>
<div class="modal-body">
  <div class="mb-1">
    <svg viewBox="0 0 24 24" width="32" fill="#0287fd">
      <g>
        <path
          d="M23.643 4.937c-.835.37-1.732.62-2.675.733.962-.576 1.7-1.49 2.048-2.578-.9.534-1.897.922-2.958 1.13-.85-.904-2.06-1.47-3.4-1.47-2.572 0-4.658 2.086-4.658 4.66 0 .364.042.718.12 1.06-3.873-.195-7.304-2.05-9.602-4.868-.4.69-.63 1.49-.63 2.342 0 1.616.823 3.043 2.072 3.878-.764-.025-1.482-.234-2.11-.583v.06c0 2.257 1.605 4.14 3.737 4.568-.392.106-.803.162-1.227.162-.3 0-.593-.028-.877-.082.593 1.85 2.313 3.198 4.352 3.234-1.595 1.25-3.604 1.995-5.786 1.995-.376 0-.747-.022-1.112-.065 2.062 1.323 4.51 2.093 7.14 2.093 8.57 0 13.255-7.098 13.255-13.254 0-.2-.005-.402-.014-.602.91-.658 1.7-1.477 2.323-2.41z">
        </path>
      </g>
    </svg>
    <h5 class="modal-note text-capitalize text-bold mt-2">create twidder account</h5>
  </div>
  <%= simple_form_for @user, url: users_path, html: {multipart: 'true', class: 'signup-form'} do |f| %>
    <%= flash_notice %>
    <%= form_error_msg(@user) %>
    <div class="mt-2">
      <%= f.input :fullname, label: 'Full name', placeholder: 'Full name', label_html: {class: 'usrform-label'}, input_html: {class: 'usrform-input'} %>
    </div>
    <div class="my-3">
      <%= f.input :username, label: 'Username', placeholder: 'userName', label_html: {class: "usrform-label"}, input_html: {class: 'usrform-input'}  %>
    </div>
    <div class="d-flex align-items-between pt-2">
      <label class="flex-fill">
        <span class="usrform-label image-upload"><span class="text-capitalize">profile </span>image:</span>
        <%= f.file_field :photo, class: 'user-imgup' %>
      </label>
      <label class="flex-fill">
        <span class="usrform-label image-upload"><span class="text-capitalize">cover </span>photo:</span>
        <%= f.file_field :cover_img, class: 'user-imgup'%>
      </label>
    </div>
    <div class="signupbtn-section d-flex flex-column align-items-center justify-content-center mt-4 pt-2">
      <div class="my-1">
        <%= f.button :submit, 'Sign up', class: 'signupsubmit-btn' %>
      </div>
      <div class="mb-1">
        <%= link_to "Log in", login_path, {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: 'my-0 optlogin-btn'} %>
        <div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content"></div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div class="modal-footer">
  <div class="mfooter-conent d-flex align-items-center justify-content-end">
    <div class="">
      <h6 class="my-0"><span class="abbrv">Twid</span> - tell what I'm doing!</h6>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>
<%= render 'form', user: @user %>
<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/new.html.erb
<div>
  <svg viewBox="0 0 24 24" width="32" fill="#0287fd">
    <g>
      <path
        d="M23.643 4.937c-.835.37-1.732.62-2.675.733.962-.576 1.7-1.49 2.048-2.578-.9.534-1.897.922-2.958 1.13-.85-.904-2.06-1.47-3.4-1.47-2.572 0-4.658 2.086-4.658 4.66 0 .364.042.718.12 1.06-3.873-.195-7.304-2.05-9.602-4.868-.4.69-.63 1.49-.63 2.342 0 1.616.823 3.043 2.072 3.878-.764-.025-1.482-.234-2.11-.583v.06c0 2.257 1.605 4.14 3.737 4.568-.392.106-.803.162-1.227.162-.3 0-.593-.028-.877-.082.593 1.85 2.313 3.198 4.352 3.234-1.595 1.25-3.604 1.995-5.786 1.995-.376 0-.747-.022-1.112-.065 2.062 1.323 4.51 2.093 7.14 2.093 8.57 0 13.255-7.098 13.255-13.254 0-.2-.005-.402-.014-.602.91-.658 1.7-1.477 2.323-2.41z"
      ></path>
    </g>
  </svg>
  <h3 class="text-capitalize">create twidder account</h3>
</div>
<%= form_error_msg(@user) %>
<%= simple_form_for @user, url: users_path, html: {multipart: 'true', class: 'signup-form'} do |f| %>
  <%= f.input :fullname, label: 'Full name', placeholder: 'Full name' %> <%= f.input :username, label: 'UserName', placeholder: 'Choose a userName' %>
  <%= f.file_field :photo, label: 'Profile z' %>
  <%= f.file_field :cover_img, label: 'Cover photo' %>
  <%= f.button :submit, 'Sign Up'%>
  <%= link_to "Log in", login_path %>
<% end %>

app/views/users/show.html.erb
<div class="wrapper">
  <%= render partial: 'shared/side_navigation' %>
  <div class="main">
    <%= render partial: 'shared/top_navigation' %>
    <div class=" mt-5 pt-3">
      <div class="d-flex">
        <div class="midcontent-left d-flex flex-column col-sm-12 col-md-8 col-xl-9">
          <div class="coverimg-container">
            <%= cover_image(@user) %>
          </div>
          <div class="twidder-menu d-flex text-capitalize">
            <div class=" px-3 mb-0 h4 menu-highlight py-3">twids</div>
            <div class="menu-inactive px-4 h4 py-3">photos</div>
            <div class="menu-inactive px-4 h4 py-3">followers</div>
            <div class="menu-inactive px-4 h4 py-3">following</div>
            <div class="menu-inactive px-4 h4 py-3">favorites</div>
            <div class="menu-inactive px-4 h4 py-3">lists</div>
          </div>
          <div class="opinion-container d-flex flex-column">
            <div class="d-flex flex-column align-items-center">
              <div class="opinion-section">
                <p class="createopinion-title mb-2 text-capitalize">twid to <%= @user.fullname %></p>
                <div class="create-opinion">
                  <%= render partial: 'shared/profile_form', locals: { opinion: @opinion } %>
                </div>
              </div>
            </div>
          </div>
          <div class="opinions-container d-flex flex-column">
            <div class="d-flex flex-column align-items-center">
              <div class="newopinion-section">
                <div class="tofollow-head d-flex justify-content-between align-items-center">
                  <div class="mb-0 pb-2 pt-1 newopinion-title">
                    <span class="text-capitalize"><%= "#{pluralize(@opinions.size, 'New twid')} "%></span> by <span class="text-capitalize"><%= @user.fullname %></span>
                  </div>
                  <div class="pb-2 pt-1">
                    <%= flash_notice %>
                    <%= flash_alert %>
                  </div> 
                </div>
                <%= render partial: 'shared/opinions' %>
              </div>
            </div>
          </div>
        </div>
        <div class="right-aside col-sm-0 col-md-4 col-xl-3">
          <div class="profile-section">
            <div class="d-flex align-items-center sbr-profile">
              <%= followprofile_toggle %>
              <div class="flex-fill d-flex flex-column align-items-center justify-content-center my-3">
                <picture class="profile-img">
                  <%= profile_image(@user) %>
                </picture>
              </div>
              <div class="flex-fill d-flex flex-column align-items-start justify-content-center py-1">
                <%= userlisticon_toggle %>
              </div>
            </div>
            <div class="profile-name d-flex flex-column justify-content-between">
              <h6 class="profile-fullname text-center text-capitalize"><%= @user.fullname %></h6>
              <h6 class="profile-username text-center">@<%= @user.username %></h6>
            </div>
          </div>
          <div class="stats-section text-capitalize">
            <div class="d-flex align-items-center ">
              <div class="stats-box flex-fill d-flex flex-column align-items-center justify-content-center">
                <h6 class="stats-figure pt-1"><%= @opinions.size %></h6>
                <h6 class="stats-category pb-1">twids</h6>
              </div>
              <div
                class="stats-box flex-fill d-flex flex-column align-items-center justify-content-center profile-stats">
                <h6 class="stats-figure pt-1"><%= @user.followed.size %></h6>
                <h6 class="stats-category pb-1">following</h6>
              </div>
              <div class="stats-box flex-fill d-flex flex-column align-items-center justify-content-center ">
                <h6 class="stats-figure pt-1"><%= @user.followers.size %></h6>
                <h6 class="stats-category pb-1">followers</h6>
              </div>
            </div>
          </div>
          <div class="followedby-section pb-3">
            <div class="followedby-head d-flex justify-content-between text-capitalize mb-3">
              <div class="sbr-title mb-0 h4 py-3">followed by</div>
              <div class=" h4 py-3">
                <a class="" href="#">
                  <i class="title-icon refresh-cw">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-refresh-cw title-icon"><polyline points="23 4 23 10 17 10"></polyline><polyline points="1 20 1 14 7 14"></polyline><path d="M3.51 9a9 9 0 0 1 14.85-3.36L23 10M1 14l4.64 4.36A9 9 0 0 0 20.49 15"></path></svg>
                  </i>
                </a>
              </div>
            </div>
            <% @followers.each do |follower| %>
              <div class="d-flex align-items-center">
                <%= link_to user_path(follower.Follower), class:'img-link' do %>
                  <picture class="followed-by-img mr-3 ml-0">
                    <%= follower_photo(follower) %>
                  </picture>
                <% end %>
                <div class="flex-fill d-flex flex-column ">
                  <h6 class="followedby-fullname text-capitalize pt-3"><%= link_to "#{follower.Follower.fullname}", user_path(follower.Follower), class:'follower-name' %></h6>
                  <h6 class="followedby-username pb-3">@<%= follower.Follower.username %></h6>
                </div>
                <div class="flex-fill d-flex flex-column align-items-end justify-content-center">
                  <div class="py-1">
                    <%= follow_toggle(follower) %>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
          <%= render partial: 'shared/trending' %>
        </div>
      </div>
    </div>
    <%= render partial: 'shared/footer' %>
  </div>
</div>