config/routes.rb
Rails.application.routes.draw do
  resources :likes
  resources :followings
  resources :users,  except: [:new]
  resource :sessions, only: [:create, :destroy]
  resources :opinions, only: [:index, :create] do
    resources :comments, only: [:create]
    resources :likes, only: [:create, :destroy]
  end

  root to: 'opinions#index'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  get '/tlogin', to: 'sessions#tnew'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  post '/create_opinion', to: 'opinions#create', as: :new_opinion
  get '/follow/:followed_id', to: 'followings#create', as: :follow
  delete '/:followed_id', to: 'followings#destroy', as: :unfollow
  get '/reply', to: 'comments#new', as: :new_reply
 end

app/views/shared/_comment_form.html.erb
<%= simple_form_for(comment, url: opinion_comments_path(opinion), :remote=> true) do |f| %>
  <%= f.input :content, as: :string, label: false, wrapper: false, placeholder: 'reply to this twid...', input_html: { class: 'comment-form' } %>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container-fluid">
    <div class="row text-muted">
      <div class="col-6 text-left">
        <p class="mb-0">
          <%= link_to root_path, class:'footer-logo' do %>
          <strong>&copy;Twidder <%= Time.now.year %></strong>
          <% end %>
        </p>
      </div>
      <div class="col-6 text-right">
        <ul class="list-inline footer-map">
          <li class="list-inline-item">
            <a class="" href="#">Support</a>
          </li>
          <li class="list-inline-item">
            <a class="" href="#">Privacy</a>
          </li>
          <li class="list-inline-item">
            <a class="" href="#">Terms</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_form.html.erb
<%= simple_form_for @opinion do |f| %>
  <%= f.error_notification %>
  <%= f.input :text, as: :string, label: false, wrapper: false, placeholder: 'tell what I\'m doing...', input_html: { class: 'opinion-form' }%>
<% end %>

app/views/shared/_opinions.html.erb
<% @opinions.each do |opinion| %>
  <div class="d-flex align-items-start py-4">
    <%= link_to user_path(opinion.author), class:'img-link' do %>
      <picture class="newopinion-img m-4 mr-3 ml-0 mt-0 rounded d-block">
        <%= author_image(opinion) %>
      </picture>
    <% end %>
    <div class="flex-fill d-flex flex-column">
      <div class="d-flex justify-content-between">
        <h6 class="newopinion-author text-capitalize"><%= link_to "#{opinion.author.fullname}", user_path(opinion.author), class:'author-name' %></h6>
        <h6 class="pl-3 newopinion-time"><%=opinion.created_at.strftime("%H") %>h</h6>
      </div>
      <p class="twid-msg py-2 pl-3 d-inline"><%= opinion.text %></p>
      <div class="d-flex justify-content-between">
        <div class="d-flex opinion-stats">
          <p class="opinion-stat1 text-capitalize pr-3"><%= like_stat(opinion) %></span>
          <p class="opinion-stat2 text-capitalize"><%= reply_stat(opinion) %></span>
        </div>
        <div class="d-flex">
          <span id="like-dislike" class="pr-4"><%= like_or_dislike_toggle(opinion) %></span>
          <div class="">
            <%= link_to new_reply_path(opinion_id: opinion.id),  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: 'text-capitalize'} do %>
              <i class="align-middle message-square pr-1"><svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="fs-18 feather feather-message-square align-middle"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"></path></svg></i><span class="text-capitalize">reply</span>
            <% end %>
              <div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                  <div class="modal-content"></div>
                </div>
              </div>
          </div>
        </div>
      </div>
      <div class="d-flex justify-content-between align-items-end">
        <div class='user-comments'>
          <%= render partial: 'comments/comment', locals: { collection: opinion.comments }, remote: true %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_profile_form.html.erb
<%= simple_form_for @opinion do |f| %>
  <%= f.error_notification %>
  <%= f.input :text, as: :string, label: false, wrapper: false, placeholder: "@#{@user.username}", value: '@user name', input_html: { class: 'opinion-form' }%>
<% end %>

app/views/shared/_side_navigation.html.erb
<nav id="sidebar" class="sidebar">
  <div class="sb-content">
    <div class="sidebar-userinfo d-flex align-items-center ">
      <picture class="sbl-userimg m-4 mr-3">
        <%= link_to user_path(current_user), class:'img-link' do %>
          <%= current_user_image(current_user) %>
        <% end %> 
        
      </picture>
      <h5 class="text-capitalize"><%= link_to "#{current_user.fullname}", user_path(current_user), class:'currentuser-name' %></h5>  
    </div>
    <div class="d-flex align-items-center sb-followinfo text-capitalize">
      <div class="flex-fill d-flex flex-column align-items-center justify-content-center following-sbdiv">
        <h6 class="sbl-statsfigure pt-3"><%= current_user.followed.size %></h6>
        <h6 class="sbl-statstitle pb-3">following</h6>
      </div>
      <div class="flex-fill d-flex flex-column align-items-center justify-content-center">
        <h6 class="sbl-statsfigure pt-3"><%= current_user.followers.size %></h6>
        <h6 class="sbl-statstitle pb-3">followers</h6>
      </div>
    </div>
    <ul class="sidebar-nav text-capitalize">
      <li class="sidebar-item">
        <%= link_to root_path, class: "sblnav-menu #{current? 'activenav-link', root_path}" do %>
          <i class="align-middle home"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home align-middle"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg></i> 
          <span class="align-middle d-inline">home</span>
        <% end %>
      </li>
      <li class="sidebar-item">
        <a class="sidebar-link">
          <i class="align-middle at-sign">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-at-sign align-middle"><circle cx="12" cy="12" r="4"></circle><path d="M16 8v5a3 3 0 0 0 6 0v-1a10 10 0 1 0-3.92 7.94"></path></svg>
          </i>
          <span class="align-middle">connect</span>
        </a>
      </li>
      <li class="sidebar-item">
        <a class="sidebar-link">
          <i class="align-middle hash"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-hash align-middle"><line x1="4" y1="9" x2="20" y2="9"></line><line x1="4" y1="15" x2="20" y2="15"></line><line x1="10" y1="3" x2="8" y2="21"></line><line x1="16" y1="3" x2="14" y2="21"></line></svg></i><span class="align-middle">discover</span>
        </a>
      </li>
      <li class="sidebar-item">
          <%= link_to user_path(current_user.id), class: "sblnav-menu #{current? 'activenav-link', user_path(current_user.id)}" do %>
            <i class="align-middle user"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-user align-middle"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path><circle cx="12" cy="7" r="4"></circle></svg></i>
            <span class="align-middle">profile</span>
          <% end %>
      </li>
      <li class="sidebar-item">
        <a class="sidebar-link">
          <i class="align-middle bar-chart-2"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-bar-chart-2 align-middle"><line x1="18" y1="20" x2="18" y2="10"></line><line x1="12" y1="20" x2="12" y2="4"></line><line x1="6" y1="20" x2="6" y2="14"></line></svg></i><span class="align-middle">statistics</span>
        </a>
      </li>
      <li class="sidebar-item">
        <a class="sidebar-link">
          <i class="align-middle more-horizontal"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-more-horizontal align-middle"><circle cx="12" cy="12" r="1"></circle><circle cx="19" cy="12" r="1"></circle><circle cx="5" cy="12" r="1"></circle></svg></i><span class="align-middle">more</span>
        </a>
      </li>
    </ul>
  </div>
</nav>

app/views/shared/_top_navigation.html.erb
<nav class="navbar navbar-expand main-nav">
  <div class="navbar-collapse collapse mainnav-icons">
    <%= link_to root_path, class:'' do %>
      <i>
        <svg viewBox="0 0 24 24" width="32" fill="#fff"><g><path d="M23.643 4.937c-.835.37-1.732.62-2.675.733.962-.576 1.7-1.49 2.048-2.578-.9.534-1.897.922-2.958 1.13-.85-.904-2.06-1.47-3.4-1.47-2.572 0-4.658 2.086-4.658 4.66 0 .364.042.718.12 1.06-3.873-.195-7.304-2.05-9.602-4.868-.4.69-.63 1.49-.63 2.342 0 1.616.823 3.043 2.072 3.878-.764-.025-1.482-.234-2.11-.583v.06c0 2.257 1.605 4.14 3.737 4.568-.392.106-.803.162-1.227.162-.3 0-.593-.028-.877-.082.593 1.85 2.313 3.198 4.352 3.234-1.595 1.25-3.604 1.995-5.786 1.995-.376 0-.747-.022-1.112-.065 2.062 1.323 4.51 2.093 7.14 2.093 8.57 0 13.255-7.098 13.255-13.254 0-.2-.005-.402-.014-.602.91-.658 1.7-1.477 2.323-2.41z"></path></g></svg>
      </i>
    <% end %>
    <ul class="navbar-nav navbar-align">
      <li class="nav-item">
        <a class="nav-icon" href="#">
          <div class="position-relative">
            <i class="align-middle message-square">
              <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-message-square align-middle"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"></path></svg>
            </i>
          </div>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-icon" href="#" id="alertsDropdown" data-toggle="dropdown">
          <div class="position-relative">
            <i class="align-middle bell">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-bell align-middle"><path d="M18 8A6 6 0 0 0 6 8c0 7-3 9-3 9h18s-3-2-3-9"></path><path d="M13.73 21a2 2 0 0 1-3.46 0"></path></svg>
            </i>
            <span class="indicator">4</span>
          </div>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-icon" href="#">
          <div class="position-relative">
            <i class="align-middle search">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-search align-middle"><circle cx="11" cy="11" r="8"></circle><line x1="21" y1="21" x2="16.65" y2="16.65"></line></svg>
            </i>
          </div>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-icon" href="#">
          <div class="position-relative">
            <i class="align-middle settings">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-settings align-middle"><circle cx="12" cy="12" r="3"></circle><path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1 0 2.83 2 2 0 0 1-2.83 0l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-2 2 2 2 0 0 1-2-2v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83 0 2 2 0 0 1 0-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1-2-2 2 2 0 0 1 2-2h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 0-2.83 2 2 0 0 1 2.83 0l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 2-2 2 2 0 0 1 2 2v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 0 2 2 0 0 1 0 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 2 2 2 2 0 0 1-2 2h-.09a1.65 1.65 0 0 0-1.51 1z"></path></svg>
            </i>
          </div>
        </a>
      </li>
      <li class="nav-item logout-link">
        <%= link_to logout_path(current_user.id), method: :delete do %>
          <div class="nav-icon">
            <div class="position-relative">
              <i class="align-middle log-out">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-log-out align-middle"><path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"></path><polyline points="16 17 21 12 16 7"></polyline><line x1="21" y1="12" x2="9" y2="12"></line></svg>
              </i>
              <span class="logouttooltip-text">Logout</span>
            </div>
          </div>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/shared/_trending.html.erb
<div class="trending-section">
  <div class="trending-head d-flex justify-content-between text-capitalize">
    <div class="sbr-title mr-5 mb-0 h4 py-3">trending</div>
    <div class=" h4 py-3">
      <a class="" href="#">
        <i class="title-icon trending-up">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-trending-up title-icon"><polyline points="23 6 13.5 15.5 8.5 10.5 1 18"></polyline><polyline points="17 6 23 6 23 12"></polyline></svg>
        </i>
      </a>
    </div>
  </div>
  <div class="">
    <div class="">
      <ul class="trending-list">
        <li class="mt-3"><a>#elections</a></li>
        <li class=""><a>#nouvelle mode</a></li>
        <li class=""><a>#des sports</a></li>
        <li class=""><a>#travel tour</a></li>
        <li class=""><a>#gagdetzone</a></li>
      </ul>
    </div>
  </div>
</div>